use_frameworks!

target 'TextFieldAction_Example' do
  pod 'TextFieldAction', :path => '../'

  target 'TextFieldAction_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
